name: qr_recipes
description: Foodccien Qr Recipes Application

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_svg: ^1.1.6
  responsive_sizer: 3.1.1
  stacked: ^3.0.1
  retrofit: ^3.3.1
  get_it: ^7.2.0
  injectable: ^2.1.0
  share_plus: 6.3.0
  flutter_cache_manager: ^3.3.0
  cached_network_image: 3.2.3
  shared_preferences: ^2.0.15
  chewie: 1.3.6
  video_player: 2.5.1
  go_router: ^12.1.1
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.2.0
  json_serializable: ^6.5.4
  flutter_native_splash: ^2.2.16
  hive_generator: ^2.0.0
  build_runner: any


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/brands/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 600
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400

flutter_native_splash:
  color: "#232323"
  android_12:
    image: assets/launcher/V12.png
    color: "#232323"
  web: false