name: qr_recipes
description: Foodccien Qr Recipes Application

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_analytics: ^10.0.6
  firebase_crashlytics: ^3.0.6
  firebase_dynamic_links: ^5.0.6
  firebase_messaging: ^14.1.2
  cloud_firestore: ^4.9.3
  cloud_firestore_web: ^3.7.2
  intl: ^0.17.0
  flutter_svg: ^1.1.6
  responsive_sizer: 3.1.1
  flutter_staggered_grid_view: ^0.6.2
  stacked: ^3.0.1
  retrofit: ^3.3.1
  get_it: ^7.2.0
  injectable: ^2.1.0
  lottie: ^2.0.0
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15
  hive: ^2.2.3
  hive_flutter: 1.1.0
  flutter_local_notifications: ^12.0.4
  flutter_keyboard_visibility: ^5.4.0
  url_launcher: ^6.1.7
  fk_user_agent: ^2.1.0
  uuid: ^3.0.7
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.3
  wakelock: ^0.6.2
  country_picker: ^2.0.20
  in_app_purchase: ^3.1.8
  flutter_webrtc: ^0.9.27
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.2.0
  json_serializable: ^6.5.4
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  change_app_package_name: ^1.1.0
  hive_generator: ^2.0.0
  build_runner: any


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 600
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icon.png"
  min_sdk_android: 19


flutter_native_splash:
  color: "#232323"
  android_12:
    image: assets/launcher/V12.png
    color: "#232323"
  web: false